### ISSUE TITLE
Update python library to BSync 2.4

### ISSUE THREAD

**Issue by nllong** [BuildingSync/bsyncpy#11]
BSyncpy needs to be regenerated for Schema Version 2.4. (Note that it also fails for 2.3.)

**Comment by JoelBender** [comment]
The generator application runs fine for me on 2.3.0 and 2.3.0-pr1, it looks like some elements like **BuildingType.MultiTenant** were removed from the former to the latter.  Is there a test file that you can post that shows the failure?

**Comment by JoelBender** [comment]
In 2.3.0, there is this:
```xml
      <xs:element name="PortfolioManager" type="auc:PortfolioManagerType" minOccurs="0">
```
which has changed to this:
```xml
      <xs:element ref="auc:PortfolioManager" minOccurs="0"/>
```
and the generator is looking for the name.  It looks like this has happened with other elements as well, **auc:FloorsAboveGrade** and **auc:FloorsBelowGrade** for example.

**Comment by nllong** [comment]
I tested 2.3 and it works fine on my machine too. However, as you noted 2.4.0 isn't working. 

```
DEBUG:root:element <Element element at 0x10179c960> None
DEBUG:root:    - elsewhere: auc:PortfolioManager
Traceback (most recent call last):
  File "bsyncpy_generator.py", line 614, in <module>
    do_complexType(child)
  File "bsyncpy_generator.py", line 410, in do_complexType
    child_element = do_element(child)
  File "bsyncpy_generator.py", line 547, in do_element
    bs_element = do_complexType(complex_type)
  File "bsyncpy_generator.py", line 381, in do_complexType
    choice_element = do_element(child)
  File "bsyncpy_generator.py", line 547, in do_element
    bs_element = do_complexType(complex_type)
  File "bsyncpy_generator.py", line 410, in do_complexType
    child_element = do_element(child)
  File "bsyncpy_generator.py", line 547, in do_element
    bs_element = do_complexType(complex_type)
  File "bsyncpy_generator.py", line 382, in do_complexType
    logging.debug(f"        - choice_element: {choice_element.element_name}")
AttributeError: 'NoneType' object has no attribute 'element_name'
```

Is this something that you can look into?

I have this branch (https://github.com/BuildingSync/bsyncpy/tree/feat/support-bsync-2.4 ) that you can use and to get started simply run:
- Download, copy, or curl a BuildingSync schema into `bsyncpy/bsync`
  - `curl -L -o bsync/BuildingSync-2.4.xsd https://github.com/BuildingSync/schema/releases/download/v2.4.0/BuildingSync.xsd`
- cd into `bsyncpy/bsync`
- Run generator: `poetry run python bsyncpy_generator.py BuildingSync-2.4.xsd`
